### PR TITLE
new icon and description

### PR DESCRIPTION
**Pull request by tessus**
- changed the icon to the one in the FF extension
- changed the description to the one used in the FF extension

### CODE REVIEW

**Comment by tessus** [comment]
ping

**Comment by binfalse** [comment]
pong ;-)

**Comment by binfalse** [comment]
sorry that it took so long, always wanted to properly update the extension, but didn't manage so far...

however, you're contributions are now merged and uploaded to chrome's web store. as soon as that's approved, a new version will pop up there :)

**Comment by binfalse** [comment]
and: thanks for your help!!

**Comment by binfalse** [comment]
I just released 2.1.1, which is now on the same state as the firefox extension :)
Let me know if you experience any issues!

**Comment by tessus** [comment]
Awesome, great. I've been doing some testing and it works better than on Firefox.

It's not really a bug, but when I click on `YOURLS admin interface`, the popup does not close on Firefox. I either have to click on the toolbar button or outside of the popup.

Thanks for the update!

**Pull request merged**
